# Generated by Django 4.1.2 on 2022-10-07 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_rename_image_place_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='discription',
            new_name='desc',
        ),
    ]
