# Generated by Django 4.1.2 on 2022-10-07 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='desc',
            new_name='desc1',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='image',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='name',
            new_name='name1',
        ),
    ]
